In [30]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [31]:
movies_df = pd.read_csv("movies.csv")
movies_df.head(10)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
5,Outer Banks,(2020– ),"\nAction, Crime, Drama",7.6,\nA group of teenagers from the wrong side of ...,"\n \n Stars:\nChase Stokes, \nMa...","25,858",50.0,NaN
6,The Last Letter from Your Lover,(2021),"\nDrama, Romance",6.8,\nA pair of interwoven stories set in the past...,\n Director:\nAugustine Frizzell\n| \n S...,"5,283",110.0,NaN
7,Dexter,(2006–2013),"\nCrime, Drama, Mystery",8.6,"\nBy day, mild-mannered Dexter is a blood-spat...","\n \n Stars:\nMichael C. Hall, \...","665,387",53.0,NaN
8,Never Have I Ever,(2020– ),\nComedy,7.9,\nThe complicated life of a modern-day first g...,\n \n Stars:\nMaitreyi Ramakrish...,"34,530",30.0,NaN
9,Virgin River,(2019– ),"\nDrama, Romance",7.4,"\nSeeking a fresh start, nurse practitioner Me...",\n \n Stars:\nAlexandra Breckenr...,"27,279",44.0,NaN

In [32]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MOVIES    9999 non-null   object
 1   YEAR      9355 non-null   object
 2   GENRE     9919 non-null   object
 3   RATING    8179 non-null   float64
 4   ONE-LINE  9999 non-null   object
 5   STARS     9999 non-null   object
 6   VOTES     8179 non-null   object
 7   RunTime   7041 non-null   float64
 8   Gross     460 non-null    object
dtypes: float64(2), object(7)
memory usage: 703.2+ KB

In [33]:
movies_df.shape

(9999, 9)

In [34]:
movies_df.isnull().sum()

MOVIES         0
YEAR         644
GENRE         80
RATING      1820
ONE-LINE       0
STARS          0
VOTES       1820
RunTime     2958
Gross       9539
dtype: int64

In [35]:
movies_df['YEAR'] = movies_df["YEAR"].astype(str)
movies_df["YEAR"].tolist()

['(2021)',
 '(2021– )',
 '(2010–2022)',
 '(2013– )',
 '(2021)',
 '(2020– )',
 '(2021)',
 '(2006–2013)',
 '(2020– )',
 '(2019– )',
 '(2021)',
 '(2016–2021)',
 '(2021)',
 '(2021– )',
 '(2011– )',
 '(2005– )',
 '(2008–2013)',
 '(2017– )',
 '(2017–2021)',
 '(2016– )',
 '(2021)',
 '(1994–2004)',
 '(2014– )',
 '(2013– )',
 '(2021– )',
 '(2021)',
 '(2013–2020)',
 '(2015– )',
 '(2005–2020)',
 '(2013– )',
 '(2021)',
 '(2016– )',
 '(2013–2022)',
 '(2003– )',
 '(2019– )',
 '(2009–2020)',
 '(I) (2018– )',
 '(2019– )',
 '(2010–2015)',
 '(2013–2022)',
 '(2011–2019)',
 '(2017–2021)',
 '(2015–2020)',
 '(2014– )',
 '(2015– )',
 '(2011– )',
 '(2017– )',
 '(2016– )',
 '(2021– )',
 '(2021)',
 '(2014– )',
 '(2005–2014)',
 '(2009–2015)',
 '(2008–2014)',
 '(2016–2018)',
 '(2009–2017)',
 '(2020)',
 '(2019– )',
 '(2018–2021)',
 '(2017–2020)',
 '(2020)',
 '(2016– )',
 '(1987–1994)',
 '(2021)',
 '(2021)',
 '(2019– )',
 '(2015– )',
 '(2018– )',
 '(2012– )',
 '(2014–2020)',
 '(2011–2018)',
 '(2005–2017)',
 '(2019– )',
 '(2021)',
 '(2021– )',
 '(2021– )',
 '(2021– )',
 '(2017)',
 '(2007–2015)',
 '(2018– )',
 '(2000–2007)',
 '(2021– )',
 '(2021– )',
 '(2021)',
 '(II) (2007– )',
 '(1993)',
 '(1999–2022)',
 '(2015–2018)',
 '(2017–2020)',
 '(2016– )',
 '(2018– )',
 '(2019– )',
 '(2014–2019)',
 '(2016– )',
 '(2013–2020)',
 '(2016)',
 '(2021)',
 '(2012–2020)',
 '(2013–2019)',
 '(2007–2012)',
 '(2020– )',
 '(2018–2021)',
 '(2011–2020)',
 '(2017– )',
 '(2010–2017)',
 '(2021)',
 '(2016–2021)',
 '(2000–2015)',
 '(2019– )',
 '(2015–2021)',
 '(2014–2020)',
 '(2001)',
 '(2019– )',
 '(1997– )',
 '(2011–2018)',
 '(2017– )',
 '(2011–2017)',
 '(2014–2020)',
 '(1993–1999)',
 '(1989–1998)',
 '(2010–2013)',
 '(2010–2020)',
 '(2015–2021)',
 '(2017– )',
 '(2003–2019)',
 '(I) (2019)',
 '(2018– )',
 '(2017–2019)',
 '(1975)',
 '(2005–2008)',
 '(2017–2019)',
 '(1995–2001)',
 '(2006)',
 '(2015–2017)',
 '(2021)',
 '(2008–2020)',
 '(1984–1996)',
 '(2021)',
 '(2010– )',
 '(2021– )',
 '(2021)',
 '(2019– )',
 '(2021– )',
 '(2014)',
 '(2017)',
 '(2000)',
 '(2013–2018)',
 '(2015– )',
 '(2021)',
 '(2019– )',
 '(2014–2019)',
 '(2009–2016)',
 '(2016–2020)',
 '(2013–2018)',
 '(2009–2015)',
 '(2021 TV Special)',
 '(2003)',
 '(2021)',
 '(2017–2021)',
 '(2006)',
 '(1998–2003)',
 '(I) (2017)',
 '(2010–2017)',
 '(1966–1969)',
 '(2009– )',
 '(2019)',
 '(1990–1991)',
 '(2021)',
 '(2017–2021)',
 '(2019– )',
 '(2021)',
 '(2012)',
 '(1995)',
 '(2013–2020)',
 '(2020–2021)',
 '(2017)',
 '(2016–2018)',
 '(2020– )',
 '(2017– )',
 '(2020)',
 '(2013–2017)',
 '(2015)',
 '(2019–2020)',
 '(2021)',
 '(2017–2018)',
 '(2020– )',
 '(2021)',
 '(2013–2015)',
 '(2012–2017)',
 '(2015)',
 '(I) (2013–2016)',
 '(2019)',
 '(2020– )',
 '(2003)',
 '(2017)',
 '(2017– )',
 '(2002)',
 '(2019)',
 '(2020)',
 '(I) (2020)',
 '(III) (2021)',
 '(2018)',
 '(2021)',
 '(2009– )',
 '(II) (2016)',
 '(1976)',
 '(1978)',
 '(2021)',
 '(2019– )',
 '(2020– )',
 '(I) (2019)',
 '(2021– )',
 '(2021)',
 '(2016–2019)',
 '(2021)',
 '(2009–2014)',
 '(2021)',
 '(2022)',
 '(2018– )',
 '(2020)',
 '(2018)',
 '(2011–2014)',
 '(2021)',
 '(2007–2013)',
 '(2019)',
 '(2017)',
 '(2016)',
 '(2021)',
 '(2006–2007)',
 '(2002–2007)',
 '(2014–2017)',
 '(I) (2020)',
 '(2013–2017)',
 '(2011–2017)',
 '(2010–2019)',
 '(2021– )',
 '(2021)',
 '(2001)',
 '(2021)',
 '(2008– )',
 '(2021)',
 '(2021– )',
 '(2013–2017)',
 '(2012–2019)',
 '(2018)',
 '(2017)',
 '(2014–2016)',
 '(2009–2012)',
 '(2018–2020)',
 '(2001–2005)',
 '(2017–2021)',
 '(2019)',
 '(2016– )',
 '(2015–2017)',
 '(2011–2015)',
 '(2015)',
 '(2014–2018)',
 '(I) (2019)',
 '(2016–2021)',
 '(2015–2021)',
 '(2002)',
 '(2020– )',
 '(2001)',
 '(2015–2019)',
 '(2018)',
 '(2017–2018)',
 '(1982–1993)',
 '(2018)',
 '(2021)',
 '(1998– )',
 '(2016– )',
 '(2017)',
 '(2015–2018)',
 '(2021– )',
 '(2019– )',
 '(2018– )',
 '(1968)',
 '(2010–2018)',
 '(2014–2021)',
 '(2021– )',
 '(2016– )',
 '(2017–2019)',
 '(2007–2010)',
 '(2016)',
 '(2018–2021)',
 '(2020)',
 '(2020)',
 '(2017)',
 '(2020– )',
 '(1978)',
 '(2014–2019)',
 '(2020)',
 '(2017–2019)',
 '(2011)',
 '(2018– )',
 '(2013–2021)',
 '(2019– )',
 '(1990–1996)',
 '(2004)',
 '(2013–2017)',
 '(2011)',
 '(2021)',
 '(2020– )',
 '(2020)',
 '(2006–2013)',
 '(2007–2014)',
 '(2019– )',
 '(1996–2001)',
 '(2017– )',
 '(2013)',
 '(2020– )',
 '(2014)',
 '(2016)',
 '(2016–2018)',
 '(2017–2021)',
 '(2019)',
 '(I) (2020)',
 '(2016– )',
 '(2021)',
 '(1978)',
 '(2020)',
 '(2021)',
 '(2018–2020)',
 '(2016– )',
 '(2008)',
 '(1999–2000)',
 '(2015–2019)',
 '(2021)',
 '(2015–2019)',
 '(I) (2017)',
 '(2014–2016)',
 '(2019)',
 '(2021– )',
 '(2020–2021)',
 '(2018)',
 '(2012–2014)',
 '(2018)',
 '(2018–2020)',
 '(2014–2018)',
 '(2018– )',
 '(II) (2016)',
 '(I) (2017)',
 '(2019)',
 '(2020– )',
 '(2018)',
 '(I) (2019)',
 '(2019)',
 '(2017)',
 '(2014–2020)',
 '(2017)',
 '(2014–2019)',
 '(I) (2013)',
 '(2020)',
 '(2019)',
 '(2016–2018)',
 '(2020)',
 '(2021– )',
 '(2012)',
 '(2016–2019)',
 '(2016–2020)',
 '(2016–2018)',
 '(2015–2017)',
 '(2020)',
 '(2020)',
 '(2021)',
 '(2016)',
 '(2017)',
 '(2012)',
 '(2011)',
 '(2012–2018)',
 '(2006)',
 '(2019)',
 '(2015–2019)',
 '(2021)',
 '(2018–2019)',
 '(2009–2013)',
 '(2016–2019)',
 '(2020)',
 '(1971)',
 '(2020)',
 '(2004– )',
 '(I) (2013)',
 '(2021)',
 '(1989)',
 '(2016)',
 '(1998)',
 '(2001–2018)',
 '(2021– )',
 '(1987–1995)',
 '(2016–2019)',
 '(I) (2014)',
 '(1998–2020)',
 '(2016–2018)',
 '(2017–2019)',
 '(2017)',
 '(2017)',
 '(2019)',
 '(2018)',
 '(2014– )',
 '(2017–2019)',
 '(2014)',
 '(2012– )',
 '(2021)',
 '(I) (2015)',
 '(2014–2019)',
 '(2004)',
 '(2018–2020)',
 '(I) (2013)',
 '(2005– )',
 '(2018)',
 '(1997)',
 '(2019– )',
 '(2014–2016)',
 '(2021– )',
 '(2004–2013)',
 '(2002– )',
 '(2021)',
 '(2020– )',
 '(2017)',
 '(2018– )',
 '(2018– )',
 '(2016)',
 '(2018)',
 '(2020)',
 '(2019– )',
 '(2019–2020)',
 '(2010)',
 '(2018)',
 '(I) (2016)',
 '(2015)',
 '(2020)',
 '(2018– )',
 '(2015–2019)',
 '(2021– )',
 '(II) (2017– )',
 '(2014–2017)',
 '(2015)',
 '(I) (2020)',
 '(2015– )',
 '(I) (2020)',
 '(1997)',
 '(2018)',
 '(2011– )',
 '(I) (2018)',
 '(I) (2021)',
 '(2016)',
 '(2020)',
 '(2004–2012)',
 '(2021– )',
 '(2021– )',
 '(2019)',
 '(2010– )',
 '(2017)',
 '(2018)',
 '(2019– )',
 '(2015–2019)',
 '(2019–2021)',
 '(2021)',
 '(2012–2018)',
 '(2016–2020)',
 '(2021)',
 '(2020)',
 '(IV) (2020)',
 '(1968)',
 '(2013– )',
 '(2016)',
 '(I) (2017)',
 '(2006–2010)',
 '(2016–2018)',
 '(2021)',
 '(2014–2016)',
 '(2013)',
 '(2006–2012)',
 '(2020– )',
 '(1968)',
 '(2017)',
 '(2015–2018)',
 '(2020)',
 '(2021)',
 '(I) (2017)',
 '(2020)',
 '(2017)',
 '(2019–2021)',
 '(2019)',
 '(1997– )',
 '(2020)',
 '(2013)',
 '(2019)',
 '(2014–2020)',
 '(2013–2015)',
 '(2016)',
 '(1997)',
 '(2020– )',
 '(2016–2018)',
 '(2020– )',
 '(2018)',
 '(2021)',
 '(2019)',
 '(2021)',
 '(2020– )',
 '(1996)',
 '(2020– )',
 '(2021)',
 '(1994–2000)',
 '(2012–2014)',
 '(2016–2018)',
 '(2021– )',
 '(2018)',
 '(2013)',
 '(2018)',
 '(1993)',
 '(2015– )',
 '(2018)',
 '(2020)',
 '(2020)',
 '(2018)',
 '(II) (2020)',
 '(1980)',
 '(2019)',
 '(I) (2011)',
 '(2020)',
 '(2021)',
 '(2016)',
 '(2014)',
 '(1995–1996)',
 '(1975)',
 '(2020)',
 '(2017)',
 '(2019)',
 '(2015–2018)',
 '(2016–2017)',
 '(2019)',
 '(2012– )',
 '(2020)',
 '(2018– )',
 '(2011– )',
 '(2015–2019)',
 '(2021)',
 '(2017)',
 '(2011)',
 '(2017)',
 '(2012)',
 '(I) (2016)',
 '(2019–2020)',
 '(2017–2019)',
 '(2020)',
 '(2018–2019)',
 '(2001)',
 '(2005–2014)',
 '(2013)',
 '(2013–2015)',
 '(1993–1996)',
 '(II) (2019– )',
 '(2016)',
 '(2021)',
 '(2009)',
 '(2018– )',
 '(2019– )',
 '(2017)',
 '(2015)',
 '(2018– )',
 '(2021)',
 '(2010)',
 '(2019)',
 '(2013–2020)',
 '(2021)',
 '(2016)',
 '(2018– )',
 '(2012)',
 '(2019)',
 '(1962)',
 '(1996)',
 '(2015–2018)',
 '(2021)',
 '(2018)',
 '(2011–2015)',
 '(1991)',
 '(2020)',
 '(2016)',
 '(2016–2017)',
 '(2020)',
 '(2020)',
 '(2009)',
 '(2019)',
 '(2020)',
 '(2010)',
 '(2022– )',
 '(2001)',
 '(2014–2018)',
 '(II) (2017)',
 '(I) (2012)',
 '(2014– )',
 '(2020– )',
 '(2018– )',
 '(2015–2019)',
 '(1984)',
 '(2021)',
 '(2011–2016)',
 '(2021– )',
 '(2009–2019)',
 '(2015)',
 '(2021)',
 '(2019)',
 '(2019)',
 '(2015)',
 '(2016)',
 '(II) (2020– )',
 '(2021– )',
 '(2020)',
 '(2021)',
 '(2016)',
 '(2019– )',
 '(2020)',
 '(2019–2021)',
 '(2006–2021)',
 '(I) (2010)',
 '(2000)',
 '(2020)',
 '(2010–2018)',
 '(2016)',
 '(2016–2019)',
 '(2021)',
 '(2018–2019)',
 '(2021)',
 '(2017)',
 '(2020)',
 '(2018)',
 '(2016)',
 '(2011–2019)',
 '(2012)',
 '(2012–2015)',
 '(2020)',
 '(2020– )',
 '(2015)',
 '(2021)',
 '(I) (2013–2014)',
 '(2017)',
 '(2020)',
 '(1960)',
 '(1988)',
 '(1995)',
 '(2021)',
 '(2020)',
 '(2015– )',
 '(2017–2018)',
 '(2007)',
 '(2018– )',
 '(2021– )',
 '(2021)',
 '(1987)',
 '(2021)',
 '(2019)',
 '(2017– )',
 '(2020– )',
 '(I) (2019)',
 '(2006)',
 '(2006)',
 '(2019)',
 '(2019)',
 '(2017)',
 '(2016–2020)',
 '(2019)',
 '(2022)',
 '(2021)',
 '(2018)',
 '(2021)',
 '(2019– )',
 '(2016)',
 '(2010–2011)',
 '(2019– )',
 '(2017–2019)',
 '(2017)',
 '(2018– )',
 '(2015– )',
 '(1969)',
 '(2016– )',
 '(2020)',
 '(2002)',
 '(2021– )',
 '(2021)',
 '(2006–2011)',
 '(2018)',
 '(II) (2019)',
 '(2020– )',
 '(2002)',
 '(2017)',
 '(2017– )',
 '(2018)',
 '(1961)',
 '(2018)',
 '(2021)',
 '(2013)',
 '(2004)',
 '(2015–2019)',
 '(1962)',
 '(2013)',
 '(2017)',
 '(2021– )',
 '(2009)',
 '(2021)',
 '(2018–2019)',
 '(2017–2019)',
 '(2017)',
 '(2021– )',
 '(2021)',
 '(2020–2021)',
 '(1979)',
 '(2020– )',
 '(2017)',
 '(II) (2022)',
 '(2019–2020)',
 '(2019– )',
 '(2011)',
 '(2016)',
 '(2016)',
 '(I) (2017)',
 '(2014–2015)',
 '(2018)',
 '(2006–2011)',
 '(2017–2020)',
 '(2016– )',
 '(2020)',
 '(2019)',
 '(2019)',
 '(2017– )',
 '(2013– )',
 '(2020)',
 '(2016)',
 '(2018– )',
 '(2019)',
 '(2019)',
 '(2015)',
 '(2019)',
 '(2021– )',
 '(2018–2019)',
 '(2020)',
 '(2015)',
 '(2018)',
 '(2011)',
 '(2010– )',
 '(2011)',
 '(2015)',
 '(2020)',
 '(1956)',
 '(2016)',
 '(2014)',
 '(2013)',
 '(2018)',
 '(2011)',
 '(2013)',
 '(2016–2019)',
 '(2020)',
 '(2018)',
 '(2017)',
 '(2019–2021)',
 '(2013–2016)',
 '(2022)',
 '(2021)',
 '(2016–2018)',
 '(III) (2018)',
 '(2018)',
 '(2020)',
 '(2020)',
 '(2014)',
 '(2018)',
 '(2013)',
 '(2020)',
 '(2014)',
 '(2010)',
 '(2020)',
 '(2005)',
 '(2013)',
 '(I) (2019)',
 '(2012)',
 '(2021)',
 '(2018)',
 '(2021)',
 '(2017– )',
 '(II) (2012– )',
 '(2011)',
 '(2021)',
 '(2019)',
 '(2004– )',
 '(1969)',
 '(2018)',
 '(2020– )',
 '(2018–2020)',
 '(2015)',
 '(2020)',
 '(II) (2013)',
 '(2017)',
 '(I) (2015)',
 '(I) (2019)',
 '(1983)',
 '(I) (2013)',
 '(2021)',
 '(2002–2019)',
 '(2020– )',
 '(2014–2016)',
 '(2017)',
 '(2008)',
 '(2016)',
 '(2021– )',
 '(2020)',
 '(2019– )',
 '(2020– )',
 '(2020)',
 '(2020)',
 '(2019)',
 '(2022)',
 '(2020)',
 '(2013)',
 '(2016–2017)',
 '(2019)',
 '(2013–2018)',
 '(2020– )',
 '(2014–2017)',
 '(2014)',
 '(2010)',
 '(2013– )',
 '(2014)',
 '(2022)',
 '(2021– )',
 '(2019)',
 '(2021)',
 '(2020–2021)',
 '(2016–2020)',
 '(2019–2020)',
 '(2020)',
 '(2016)',
 '(2020)',
 '(2005–2008)',
 '(2019)',
 '(1989)',
 '(2022)',
 '(2015)',
 '(2019)',
 '(2010–2020)',
 '(2020)',
 '(2011–2016)',
 '(2017)',
 '(2016)',
 '(2013 TV Movie)',
 '(2020)',
 '(2021)',
 '(2012)',
 '(2016)',
 '(2021– )',
 '(2018)',
 '(2014)',
 '(2021)',
 '(II) (2015)',
 '(2016)',
 '(I) (2012–2015)',
 '(I) (2015)',
 '(2020– )',
 '(1975–1979)',
 '(2016–2018)',
 '(2020)',
 '(2021– )',
 '(2016)',
 '(2019)',
 '(2016)',
 '(2019)',
 '(2005)',
 '(2021– )',
 '(2016–2020)',
 '(2018)',
 '(2021)',
 '(2013–2017)',
 '(1984)',
 '(2013)',
 '(2012)',
 '(1990)',
 '(2021)',
 '(2019–2021)',
 '(2015)',
 '(2020)',
 'nan',
 '(2018–2020)',
 '(I) (2018)',
 '(2021– )',
 '(1997)',
 '(2016)',
 '(2012)',
 '(2017–2020)',
 '(2007)',
 '(2019– )',
 '(I) (2019)',
 '(II) (2018)',
 '(2019– )',
 '(2017)',
 '(2019)',
 '(II) (2018)',
 '(2020)',
 '(2018)',
 '(2016– )',
 '(2008)',
 '(2018)',
 '(I) (2018)',
 '(2019)',
 '(2021– )',
 '(2017–2020)',
 '(2019– )',
 '(2005)',
 '(2016)',
 '(2012)',
 '(2018–2021)',
 '(2020)',
 '(2009)',
 '(IV) (2021)',
 '(2018)',
 '(2018)',
 '(2019)',
 '(2018– )',
 '(2020– )',
 '(2018)',
 '(2017)',
 '(2015–2018)',
 '(I) (2017)',
 '(2018)',
 '(2020)',
 '(2021)',
 '(2018)',
 '(I) (2014)',
 '(2018)',
 '(2019)',
 '(2020)',
 '(2016)',
 '(2017– )',
 '(2011)',
 '(2019– )',
 '(2014–2015)',
 '(2020– )',
 '(2020–2021)',
 '(2021)',
 '(2018)',
 '(2020)',
 '(2020– )',
 '(2018–2020)',
 '(2017)',
 '(I) (2019)',
 '(2013)',
 '(2021– )',
 '(2018– )',
 '(2019– )',
 '(2016–2020)',
 '(2019– )',
 '(2021)',
 '(2019– )',
 '(2021)',
 '(2006)',
 '(2020)',
 '(II) (2016)',
 '(2020)',
 '(2018)',
 '(2021)',
 '(2017– )',
 '(2018)',
 '(2015)',
 '(2021)',
 '(2020)',
 '(2017)',
 '(2016)',
 '(2016)',
 '(2018)',
 '(I) (2017)',
 '(2020)',
 '(1998)',
 '(2018)',
 '(2017–2019)',
 '(2015–2016)',
 '(2016)',
 '(2016)',
 '(2019)',
 '(2019)',
 '(2019)',
 '(2017)',
 '(2021)',
 '(2018)',
 '(2020)',
 '(2020)',
 '(I) (2020)',
 '(2017)',
 '(2019)',
 '(2020)',
 '(2018–2020)',
 '(1995–1998)',
 '(1969)',
 '(II) (2016)',
 '(I) (2012)',
 '(2020)',
 '(2019)',
 '(2011)',
 '(1997)',
 '(2013)',
 '(II) (2018)',
 '(2018–2021)',
 '(2020)',
 '(1986)',
 ...]

In [36]:
def clean_year(value):
    if "("in value or ")" in value:
        value = value.replace("(", "").replace(")", "")
    if "-" in value or "-" in value:
        value = value.split("-")[0].split("-")[0]
    digit = "".join([i for i in value if i.isdigit()])
    if digit:
        return int(digit)
    else:
        return np.nan
movies_df["YEAR"] = movies_df["YEAR"].apply(clean_year)
movies_df["YEAR"]

0           2021.0
1           2021.0
2       20102022.0
3           2013.0
4           2021.0
           ...
9994        2021.0
9995        2021.0
9996        2022.0
9997        2021.0
9998        2021.0
Name: YEAR, Length: 9999, dtype: float64

In [37]:
movies_df['YEAR'] = pd.to_numeric(movies_df['YEAR'], errors='coerce')

filtered_df = movies_df[(movies_df['YEAR'] >= 2010) & (movies_df['YEAR'] <= 2022)]
filtered_df

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,2021.0,"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,2021.0,"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
3,Rick and Morty,2013.0,"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,2021.0,"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
5,Outer Banks,2020.0,"\nAction, Crime, Drama",7.6,\nA group of teenagers from the wrong side of ...,"\n \n Stars:\nChase Stokes, \nMa...","25,858",50.0,NaN
...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,2021.0,"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
9995,Arcane,2021.0,"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
9996,Heart of Invictus,2022.0,"\nDocumentary, Sport",NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN
9997,The Imperfects,2021.0,"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN
9998,The Imperfects,2021.0,"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN

In [38]:
movies_df.dropna(subset=["YEAR"], inplace=True)

In [39]:
movies_df['GENRE'] = movies_df['GENRE'].astype(str)

movies_df['GENRE'].replace({
    "nan": np.nan,
    "\n": ""
}, inplace=True)

movies_df['GENRE'] = movies_df['GENRE'].dropna().apply(lambda x: [g.strip() for g in x.split(',')])

movies_df = movies_df.explode('GENRE')

movies_df = movies_df.dropna(subset=['GENRE']).reset_index(drop=True)

movies_df.head(10)

C:\Users\USER\AppData\Local\Temp\ipykernel_5768\841872157.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movies_df['GENRE'].replace({

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,2021.0,Action,6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Blood Red Sky,2021.0,Horror,6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
2,Blood Red Sky,2021.0,Thriller,6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
3,Masters of the Universe: Revelation,2021.0,Animation,5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
4,Masters of the Universe: Revelation,2021.0,Action,5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
5,Masters of the Universe: Revelation,2021.0,Adventure,5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
6,The Walking Dead,20102022.0,Drama,8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
7,The Walking Dead,20102022.0,Horror,8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
8,The Walking Dead,20102022.0,Thriller,8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
9,Rick and Morty,2013.0,Animation,9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN

In [40]:
movies_df["RATING"]= movies_df["RATING"].replace({"NaN": np.nan})
movies_df["RATING"]

0        6.1
1        6.1
2        6.1
3        5.0
4        5.0
        ...
20936    NaN
20937    NaN
20938    NaN
20939    NaN
20940    NaN
Name: RATING, Length: 20941, dtype: float64

In [41]:
movies_df['RATING'] = pd.to_numeric(movies_df['RATING'], errors='coerce')
movies_df["RATING"]= movies_df['RATING'].fillna(movies_df['RATING'].mean()).round(2)
movies_df["RATING"]

0        6.10
1        6.10
2        6.10
3        5.00
4        5.00
         ...
20936    6.99
20937    6.99
20938    6.99
20939    6.99
20940    6.99
Name: RATING, Length: 20941, dtype: float64

In [42]:
movies_df["VOTES"]

0        21,062
1        21,062
2        21,062
3        17,870
4        17,870
          ...
20936       NaN
20937       NaN
20938       NaN
20939       NaN
20940       NaN
Name: VOTES, Length: 20941, dtype: object

In [43]:
movies_df["VOTES"].replace({"NaN": np.nan}, inplace=True)

In [44]:
movies_df['VOTES'] = movies_df['VOTES'].astype(str).str.replace(r',', '', regex=False)

movies_df["VOTES"]

0        21062
1        21062
2        21062
3        17870
4        17870
         ...
20936      nan
20937      nan
20938      nan
20939      nan
20940      nan
Name: VOTES, Length: 20941, dtype: object

In [45]:
movies_df['VOTES'] = pd.to_numeric(movies_df['VOTES'], errors='coerce')
movies_df['VOTES'].fillna(movies_df["VOTES"].mode()[0],inplace=True)
movies_df["VOTES"].tolist()

C:\Users\USER\AppData\Local\Temp\ipykernel_5768\574662423.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movies_df['VOTES'].fillna(movies_df["VOTES"].mode()[0],inplace=True)

[21062.0,
 21062.0,
 21062.0,
 17870.0,
 17870.0,
 17870.0,
 885805.0,
 885805.0,
 885805.0,
 414849.0,
 414849.0,
 414849.0,
 7.0,
 7.0,
 7.0,
 25858.0,
 25858.0,
 25858.0,
 5283.0,
 5283.0,
 665387.0,
 665387.0,
 665387.0,
 34530.0,
 27279.0,
 27279.0,
 17989.0,
 17989.0,
 17989.0,
 264222.0,
 264222.0,
 264222.0,
 50148.0,
 50148.0,
 50148.0,
 12172.0,
 12172.0,
 12172.0,
 286488.0,
 286488.0,
 286488.0,
 266258.0,
 266258.0,
 1552311.0,
 1552311.0,
 1552311.0,
 70871.0,
 71544.0,
 71544.0,
 885856.0,
 885856.0,
 885856.0,
 36634.0,
 36634.0,
 36634.0,
 880918.0,
 880918.0,
 320264.0,
 320264.0,
 320264.0,
 393414.0,
 393414.0,
 7.0,
 7.0,
 7.0,
 4681.0,
 4681.0,
 4681.0,
 459913.0,
 459913.0,
 459913.0,
 347857.0,
 347857.0,
 404273.0,
 404273.0,
 404273.0,
 213522.0,
 213522.0,
 213522.0,
 27447.0,
 27447.0,
 26926.0,
 26926.0,
 248583.0,
 248583.0,
 125619.0,
 125619.0,
 125619.0,
 34906.0,
 34906.0,
 34906.0,
 378030.0,
 378030.0,
 378030.0,
 73656.0,
 73656.0,
 73656.0,
 336484.0,
 336484.0,
 336484.0,
 171804.0,
 171804.0,
 242582.0,
 242582.0,
 242582.0,
 374263.0,
 374263.0,
 341858.0,
 341858.0,
 341858.0,
 90728.0,
 134991.0,
 134991.0,
 134991.0,
 94650.0,
 94650.0,
 94650.0,
 469407.0,
 469407.0,
 469407.0,
 206090.0,
 206090.0,
 206090.0,
 169517.0,
 169517.0,
 169517.0,
 37142.0,
 37142.0,
 37142.0,
 132378.0,
 132378.0,
 132378.0,
 341221.0,
 341221.0,
 341221.0,
 624036.0,
 624036.0,
 231013.0,
 270445.0,
 270445.0,
 270445.0,
 22971.0,
 22971.0,
 293434.0,
 293434.0,
 293434.0,
 63620.0,
 63620.0,
 23960.0,
 23960.0,
 23960.0,
 38618.0,
 38618.0,
 38618.0,
 266386.0,
 266386.0,
 266386.0,
 336801.0,
 95897.0,
 95897.0,
 95897.0,
 106181.0,
 106181.0,
 106181.0,
 2606.0,
 2606.0,
 1591.0,
 1591.0,
 15048.0,
 15048.0,
 15048.0,
 119644.0,
 119644.0,
 119644.0,
 27709.0,
 46751.0,
 46751.0,
 46751.0,
 226962.0,
 226962.0,
 226962.0,
 200421.0,
 492438.0,
 492438.0,
 492438.0,
 177274.0,
 177274.0,
 8822.0,
 8822.0,
 8822.0,
 848.0,
 848.0,
 848.0,
 16954.0,
 16954.0,
 60283.0,
 60283.0,
 60283.0,
 205979.0,
 205979.0,
 205979.0,
 216203.0,
 59730.0,
 59730.0,
 59730.0,
 106650.0,
 106650.0,
 6940.0,
 6940.0,
 6940.0,
 84428.0,
 84428.0,
 84428.0,
 2353.0,
 2353.0,
 2353.0,
 11764.0,
 11764.0,
 897444.0,
 897444.0,
 897444.0,
 312584.0,
 312584.0,
 374963.0,
 374963.0,
 374963.0,
 312629.0,
 312629.0,
 312629.0,
 44367.0,
 44367.0,
 44367.0,
 122268.0,
 122268.0,
 122268.0,
 6388.0,
 6388.0,
 6388.0,
 216458.0,
 216458.0,
 216458.0,
 74094.0,
 205119.0,
 205119.0,
 205119.0,
 237601.0,
 237601.0,
 237601.0,
 20561.0,
 20561.0,
 20561.0,
 414712.0,
 414712.0,
 414712.0,
 284554.0,
 284554.0,
 284554.0,
 159666.0,
 159666.0,
 83944.0,
 83944.0,
 33440.0,
 33440.0,
 322307.0,
 322307.0,
 322307.0,
 126112.0,
 126112.0,
 126112.0,
 839029.0,
 839029.0,
 839029.0,
 1336.0,
 23318.0,
 23318.0,
 23318.0,
 78589.0,
 78589.0,
 78589.0,
 175513.0,
 175513.0,
 175513.0,
 115373.0,
 115373.0,
 115373.0,
 124318.0,
 124318.0,
 124318.0,
 1713028.0,
 1713028.0,
 1713028.0,
 8095.0,
 340148.0,
 340148.0,
 212616.0,
 212616.0,
 212616.0,
 101079.0,
 101079.0,
 101079.0,
 132950.0,
 132950.0,
 132950.0,
 136135.0,
 136135.0,
 136135.0,
 55687.0,
 55687.0,
 55687.0,
 264801.0,
 228484.0,
 228484.0,
 228484.0,
 68627.0,
 68627.0,
 68627.0,
 8268.0,
 8268.0,
 8268.0,
 96901.0,
 96901.0,
 96901.0,
 284373.0,
 99351.0,
 99351.0,
 99351.0,
 157666.0,
 157666.0,
 157666.0,
 235694.0,
 235694.0,
 235694.0,
 558731.0,
 558731.0,
 265845.0,
 265845.0,
 265845.0,
 194777.0,
 194777.0,
 194777.0,
 61917.0,
 61917.0,
 61917.0,
 1227522.0,
 1227522.0,
 1227522.0,
 375261.0,
 375261.0,
 375261.0,
 33936.0,
 33936.0,
 33936.0,
 71904.0,
 71904.0,
 71904.0,
 20330.0,
 20330.0,
 20330.0,
 26508.0,
 26508.0,
 34064.0,
 34064.0,
 34064.0,
 846.0,
 846.0,
 846.0,
 57048.0,
 57048.0,
 57048.0,
 25453.0,
 25453.0,
 25453.0,
 8391.0,
 8391.0,
 8391.0,
 895888.0,
 895888.0,
 895888.0,
 337900.0,
 337900.0,
 337900.0,
 517014.0,
 517014.0,
 517014.0,
 476656.0,
 8300.0,
 8300.0,
 8300.0,
 8466.0,
 8466.0,
 46259.0,
 46259.0,
 46259.0,
 41758.0,
 70021.0,
 70021.0,
 70021.0,
 127417.0,
 127417.0,
 127417.0,
 88962.0,
 88962.0,
 88962.0,
 139934.0,
 139934.0,
 139934.0,
 31108.0,
 31108.0,
 31108.0,
 1034554.0,
 1034554.0,
 1034554.0,
 398.0,
 398.0,
 398.0,
 51802.0,
 51802.0,
 51802.0,
 751815.0,
 751815.0,
 38117.0,
 38117.0,
 480607.0,
 155875.0,
 155875.0,
 155875.0,
 76213.0,
 76213.0,
 76213.0,
 141784.0,
 141784.0,
 141784.0,
 363012.0,
 363012.0,
 363012.0,
 182173.0,
 182173.0,
 182173.0,
 69482.0,
 69482.0,
 69482.0,
 16183.0,
 16183.0,
 120364.0,
 120364.0,
 120364.0,
 315.0,
 774632.0,
 774632.0,
 194461.0,
 194461.0,
 79618.0,
 79618.0,
 2923.0,
 2923.0,
 2923.0,
 170844.0,
 170844.0,
 170844.0,
 14759.0,
 14759.0,
 14759.0,
 39433.0,
 39433.0,
 39433.0,
 12896.0,
 108684.0,
 108684.0,
 108684.0,
 100611.0,
 100611.0,
 100611.0,
 371194.0,
 371194.0,
 371194.0,
 5667.0,
 5667.0,
 5667.0,
 8099.0,
 8099.0,
 118859.0,
 118859.0,
 118859.0,
 10008.0,
 10008.0,
 10008.0,
 18149.0,
 18149.0,
 18149.0,
 236161.0,
 236161.0,
 236161.0,
 30685.0,
 30685.0,
 30685.0,
 387903.0,
 387903.0,
 387903.0,
 89590.0,
 89590.0,
 89590.0,
 345455.0,
 345455.0,
 345455.0,
 25386.0,
 25386.0,
 25386.0,
 1691777.0,
 1691777.0,
 1691777.0,
 468655.0,
 468655.0,
 468655.0,
 16666.0,
 709684.0,
 709684.0,
 709684.0,
 205638.0,
 205638.0,
 205638.0,
 109059.0,
 109059.0,
 109059.0,
 100693.0,
 100693.0,
 100693.0,
 16262.0,
 16262.0,
 16262.0,
 195117.0,
 195117.0,
 195117.0,
 24250.0,
 24250.0,
 24250.0,
 49943.0,
 49943.0,
 49943.0,
 623912.0,
 623912.0,
 752553.0,
 752553.0,
 250587.0,
 250587.0,
 19980.0,
 19980.0,
 19980.0,
 3653.0,
 31200.0,
 31200.0,
 31200.0,
 97848.0,
 97848.0,
 97848.0,
 35247.0,
 35247.0,
 31953.0,
 31953.0,
 31953.0,
 81326.0,
 81326.0,
 81326.0,
 7.0,
 7.0,
 7.0,
 122230.0,
 122230.0,
 122230.0,
 60598.0,
 60598.0,
 60598.0,
 7.0,
 7.0,
 7.0,
 18088.0,
 18088.0,
 141605.0,
 141605.0,
 141605.0,
 390167.0,
 390167.0,
 390167.0,
 102312.0,
 102312.0,
 102312.0,
 7.0,
 77286.0,
 150455.0,
 150455.0,
 215795.0,
 215795.0,
 215795.0,
 697750.0,
 697750.0,
 697750.0,
 1976.0,
 1976.0,
 1976.0,
 262556.0,
 262556.0,
 262556.0,
 79832.0,
 79832.0,
 79832.0,
 96550.0,
 96550.0,
 55389.0,
 55389.0,
 104501.0,
 104501.0,
 104501.0,
 111716.0,
 111716.0,
 111716.0,
 125749.0,
 125749.0,
 125749.0,
 592.0,
 592.0,
 7.0,
 7.0,
 7.0,
 682809.0,
 682809.0,
 682809.0,
 7.0,
 7.0,
 7.0,
 11437.0,
 11437.0,
 11437.0,
 15262.0,
 15262.0,
 15262.0,
 7128.0,
 7128.0,
 7128.0,
 45045.0,
 45045.0,
 103707.0,
 103707.0,
 103707.0,
 43896.0,
 43896.0,
 43896.0,
 294292.0,
 294292.0,
 294292.0,
 23317.0,
 23317.0,
 23317.0,
 134855.0,
 134855.0,
 134855.0,
 149002.0,
 149002.0,
 149002.0,
 48148.0,
 48148.0,
 48148.0,
 13218.0,
 13218.0,
 13218.0,
 239770.0,
 239770.0,
 239770.0,
 83137.0,
 83137.0,
 83137.0,
 46111.0,
 46111.0,
 114932.0,
 114932.0,
 114932.0,
 732244.0,
 732244.0,
 732244.0,
 34226.0,
 34226.0,
 34226.0,
 80553.0,
 80553.0,
 80553.0,
 12443.0,
 41520.0,
 1529752.0,
 1529752.0,
 1529752.0,
 5342.0,
 5342.0,
 195752.0,
 195752.0,
 198056.0,
 198056.0,
 198056.0,
 9263.0,
 9263.0,
 9263.0,
 28093.0,
 28093.0,
 28093.0,
 49886.0,
 49886.0,
 197909.0,
 197909.0,
 197909.0,
 4485.0,
 4485.0,
 4485.0,
 157990.0,
 157990.0,
 1327.0,
 276173.0,
 276173.0,
 276173.0,
 144032.0,
 144032.0,
 144032.0,
 3700.0,
 3700.0,
 3700.0,
 61944.0,
 61944.0,
 61944.0,
 64838.0,
 64838.0,
 622998.0,
 622998.0,
 81525.0,
 81525.0,
 81525.0,
 26282.0,
 26282.0,
 26282.0,
 742.0,
 12031.0,
 12031.0,
 12031.0,
 43433.0,
 43433.0,
 70514.0,
 70514.0,
 70514.0,
 657423.0,
 657423.0,
 657423.0,
 23179.0,
 941.0,
 941.0,
 941.0,
 69037.0,
 69037.0,
 69037.0,
 201141.0,
 201141.0,
 201141.0,
 55757.0,
 55757.0,
 55757.0,
 115289.0,
 42129.0,
 40186.0,
 40186.0,
 40186.0,
 157802.0,
 157802.0,
 157802.0,
 399157.0,
 399157.0,
 399157.0,
 76255.0,
 76255.0,
 76255.0,
 18080.0,
 18080.0,
 91972.0,
 91972.0,
 125167.0,
 706053.0,
 706053.0,
 706053.0,
 100394.0,
 100394.0,
 100394.0,
 386263.0,
 386263.0,
 386263.0,
 47174.0,
 47174.0,
 47174.0,
 7563.0,
 7563.0,
 7563.0,
 174406.0,
 174406.0,
 138970.0,
 174076.0,
 174076.0,
 7429.0,
 7429.0,
 7429.0,
 48780.0,
 48780.0,
 48780.0,
 61304.0,
 61304.0,
 61304.0,
 335946.0,
 335946.0,
 335946.0,
 47717.0,
 47717.0,
 47717.0,
 286734.0,
 286734.0,
 217433.0,
 217433.0,
 217433.0,
 49197.0,
 49197.0,
 49197.0,
 23354.0,
 23354.0,
 23354.0,
 103143.0,
 1978.0,
 1978.0,
 1978.0,
 5407.0,
 5407.0,
 27918.0,
 27918.0,
 27918.0,
 73931.0,
 73931.0,
 73931.0,
 145206.0,
 145206.0,
 145206.0,
 4682.0,
 4682.0,
 4682.0,
 82557.0,
 82557.0,
 82557.0,
 26485.0,
 26485.0,
 26485.0,
 391033.0,
 391033.0,
 391033.0,
 133607.0,
 133607.0,
 62258.0,
 62258.0,
 62258.0,
 1741.0,
 1741.0,
 1741.0,
 27588.0,
 27588.0,
 27588.0,
 284484.0,
 284484.0,
 284484.0,
 115055.0,
 115055.0,
 115055.0,
 81658.0,
 81658.0,
 30827.0,
 30827.0,
 30827.0,
 7949.0,
 7949.0,
 7949.0,
 103187.0,
 103187.0,
 103187.0,
 109581.0,
 109581.0,
 109581.0,
 297927.0,
 297927.0,
 11967.0,
 11967.0,
 11967.0,
 48387.0,
 48387.0,
 48387.0,
 24293.0,
 211816.0,
 211816.0,
 211816.0,
 79593.0,
 79593.0,
 266307.0,
 266307.0,
 266307.0,
 44914.0,
 44914.0,
 44914.0,
 293459.0,
 293459.0,
 293459.0,
 62113.0,
 62113.0,
 200029.0,
 200029.0,
 200029.0,
 56997.0,
 56997.0,
 15250.0,
 15250.0,
 15250.0,
 218337.0,
 218337.0,
 218337.0,
 31182.0,
 31182.0,
 31182.0,
 586769.0,
 586769.0,
 586769.0,
 77872.0,
 77872.0,
 77872.0,
 62393.0,
 62393.0,
 62393.0,
 39010.0,
 39010.0,
 39010.0,
 77727.0,
 77727.0,
 77727.0,
 207.0,
 207.0,
 207.0,
 208903.0,
 208903.0,
 208903.0,
 56183.0,
 56183.0,
 56183.0,
 35091.0,
 35091.0,
 35091.0,
 33000.0,
 33000.0,
 23095.0,
 23095.0,
 23095.0,
 153211.0,
 153211.0,
 153211.0,
 3214.0,
 3214.0,
 3214.0,
 36937.0,
 36937.0,
 36937.0,
 295435.0,
 295435.0,
 295435.0,
 60354.0,
 60354.0,
 60354.0,
 328550.0,
 328550.0,
 328550.0,
 290444.0,
 290444.0,
 23735.0,
 23735.0,
 23735.0,
 117889.0,
 117889.0,
 183495.0,
 183495.0,
 183495.0,
 35660.0,
 35660.0,
 35660.0,
 10460.0,
 10460.0,
 40731.0,
 40731.0,
 40731.0,
 95735.0,
 95735.0,
 95735.0,
 16659.0,
 16659.0,
 16659.0,
 71640.0,
 71640.0,
 186202.0,
 186202.0,
 186202.0,
 ...]

In [46]:
movies_df["RunTime"].tolist()
movies_df["RunTime"] = movies_df["RunTime"].replace({"NaN":np.nan})

In [47]:
movies_df["RunTime"]= movies_df["RunTime"].fillna(movies_df["RunTime"].mean()).round(1)
movies_df["RunTime"]

0        121.0
1        121.0
2        121.0
3         25.0
4         25.0
         ...
20936     67.3
20937     67.3
20938     67.3
20939     67.3
20940     67.3
Name: RunTime, Length: 20941, dtype: float64

In [48]:
movies_df["Gross"].tolist()

[nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$75.47M',
 '$75.47M',
 '$75.47M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$402.45M',
 '$402.45M',
 '$402.45M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$89.22M',
 '$89.22M',
 '$89.22M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$315.54M',
 '$315.54M',
 '$315.54M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$57.01M',
 '$57.01M',
 '$57.01M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$260.00M',
 '$260.00M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$132.38M',
 '$132.38M',
 '$132.38M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$167.77M',
 '$167.77M',
 '$167.77M',
 '$404.52M',
 '$404.52M',
 '$404.52M',
 '$15.07M',
 '$15.07M',
 '$15.07M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$70.10M',
 '$70.10M',
 '$70.10M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$210.61M',
 '$210.61M',
 nan,
 nan,
 '$327.48M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$390.53M',
 '$390.53M',
 '$390.53M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$303.00M',
 '$303.00M',
 '$56.63M',
 '$56.63M',
 nan,
 nan,
 nan,
 nan,
 nan,
 '$58.06M',
 '$58.06M',
 '$58.06M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$353.01M',
 '$353.01M',
 '$353.01M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$46.89M',
 '$46.89M',
 '$46.89M',
 nan,
 nan,
 nan,
 '$7.00M',
 '$7.00M',
 '$7.00M',
 nan,
 nan,
 nan,
 '$377.85M',
 '$377.85M',
 '$377.85M',
 '$107.83M',
 '$107.83M',
 '$107.83M',
 nan,
 '$403.71M',
 '$403.71M',
 '$403.71M',
 '$316.83M',
 '$316.83M',
 '$316.83M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$100.55M',
 '$100.55M',
 '$28.26M',
 '$28.26M',
 '$188.76M',
 '$188.76M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$213.52M',
 '$213.52M',
 '$213.52M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$226.01M',
 '$226.01M',
 '$226.01M',
 '$408.08M',
 '$408.08M',
 '$408.08M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$10.06M',
 '$10.06M',
 '$10.06M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$14.84M',
 '$14.84M',
 '$14.84M',
 '$168.05M',
 '$168.05M',
 '$168.05M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$183.64M',
 '$183.64M',
 '$183.64M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$342.55M',
 '$342.55M',
 '$342.55M',
 nan,
 nan,
 '$96.52M',
 '$96.52M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$140.22M',
 '$140.22M',
 '$140.22M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$172.56M',
 '$172.56M',
 '$172.56M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$56.95M',
 '$56.95M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$330.36M',
 '$330.36M',
 '$330.36M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$17.80M',
 '$17.80M',
 '$17.80M',
 nan,
 nan,
 nan,
 '$0.20M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$56.82M',
 '$56.82M',
 '$56.82M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$66.21M',
 '$66.21M',
 '$66.21M',
 nan,
 nan,
 nan,
 '$75.61M',
 '$75.61M',
 '$75.61M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$4.56M',
 '$4.56M',
 '$4.56M',
 nan,
 nan,
 nan,
 '$106.58M',
 '$106.58M',
 '$5.02M',
 '$5.02M',
 '$5.02M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$22.68M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$102.92M',
 '$102.92M',
 '$102.92M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$110.52M',
 '$110.52M',
 '$110.52M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$504.01M',
 '$504.01M',
 '$504.01M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$26.86M',
 '$26.86M',
 '$26.86M',
 nan,
 nan,
 '$2.00M',
 '$2.00M',
 '$2.00M',
 nan,
 nan,
 nan,
 '$32.73M',
 '$32.73M',
 '$32.73M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$33.80M',
 '$33.80M',
 '$33.80M',
 nan,
 nan,
 nan,
 '$400.74M',
 '$400.74M',
 '$400.74M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$19.02M',
 '$19.02M',
 '$19.02M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$36.26M',
 '$36.26M',
 '$36.26M',
 '$6.67M',
 '$6.67M',
 '$6.67M',
 '$45.51M',
 '$45.51M',
 '$45.51M',
 '$75.66M',
 '$75.66M',
 nan,
 nan,
 nan,
 '$0.33M',
 '$0.33M',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '$4.00M',
 '$4.00M',
 '$4.00M',
 ...]

In [49]:
movies_df["Gross"]= movies_df["Gross"].replace(r"[$M]" ,"", regex= True)
movies_df["Gross"].tolist()

[nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '75.47',
 '75.47',
 '75.47',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '402.45',
 '402.45',
 '402.45',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '89.22',
 '89.22',
 '89.22',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '315.54',
 '315.54',
 '315.54',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '57.01',
 '57.01',
 '57.01',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '260.00',
 '260.00',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '132.38',
 '132.38',
 '132.38',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '167.77',
 '167.77',
 '167.77',
 '404.52',
 '404.52',
 '404.52',
 '15.07',
 '15.07',
 '15.07',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '70.10',
 '70.10',
 '70.10',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '210.61',
 '210.61',
 nan,
 nan,
 '327.48',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '390.53',
 '390.53',
 '390.53',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '303.00',
 '303.00',
 '56.63',
 '56.63',
 nan,
 nan,
 nan,
 nan,
 nan,
 '58.06',
 '58.06',
 '58.06',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '353.01',
 '353.01',
 '353.01',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '46.89',
 '46.89',
 '46.89',
 nan,
 nan,
 nan,
 '7.00',
 '7.00',
 '7.00',
 nan,
 nan,
 nan,
 '377.85',
 '377.85',
 '377.85',
 '107.83',
 '107.83',
 '107.83',
 nan,
 '403.71',
 '403.71',
 '403.71',
 '316.83',
 '316.83',
 '316.83',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '100.55',
 '100.55',
 '28.26',
 '28.26',
 '188.76',
 '188.76',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '213.52',
 '213.52',
 '213.52',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '226.01',
 '226.01',
 '226.01',
 '408.08',
 '408.08',
 '408.08',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '10.06',
 '10.06',
 '10.06',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '14.84',
 '14.84',
 '14.84',
 '168.05',
 '168.05',
 '168.05',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '183.64',
 '183.64',
 '183.64',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '342.55',
 '342.55',
 '342.55',
 nan,
 nan,
 '96.52',
 '96.52',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '140.22',
 '140.22',
 '140.22',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '172.56',
 '172.56',
 '172.56',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '56.95',
 '56.95',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '330.36',
 '330.36',
 '330.36',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '17.80',
 '17.80',
 '17.80',
 nan,
 nan,
 nan,
 '0.20',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '56.82',
 '56.82',
 '56.82',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '66.21',
 '66.21',
 '66.21',
 nan,
 nan,
 nan,
 '75.61',
 '75.61',
 '75.61',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '4.56',
 '4.56',
 '4.56',
 nan,
 nan,
 nan,
 '106.58',
 '106.58',
 '5.02',
 '5.02',
 '5.02',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '22.68',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '102.92',
 '102.92',
 '102.92',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '110.52',
 '110.52',
 '110.52',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '504.01',
 '504.01',
 '504.01',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '26.86',
 '26.86',
 '26.86',
 nan,
 nan,
 '2.00',
 '2.00',
 '2.00',
 nan,
 nan,
 nan,
 '32.73',
 '32.73',
 '32.73',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '33.80',
 '33.80',
 '33.80',
 nan,
 nan,
 nan,
 '400.74',
 '400.74',
 '400.74',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '19.02',
 '19.02',
 '19.02',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '36.26',
 '36.26',
 '36.26',
 '6.67',
 '6.67',
 '6.67',
 '45.51',
 '45.51',
 '45.51',
 '75.66',
 '75.66',
 nan,
 nan,
 nan,
 '0.33',
 '0.33',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '4.00',
 '4.00',
 '4.00',
 ...]

In [50]:
movies_df["Gross"]= movies_df["Gross"].replace({"NaN": np.nan})

In [51]:
movies_df["Gross"] = pd.to_numeric(movies_df["Gross"], errors="coerce")

In [52]:
movies_df["Gross"] = movies_df["Gross"].fillna(movies_df["Gross"].mean()).round(2)
movies_df["Gross"]

0        47.58
1        47.58
2        47.58
3        47.58
4        47.58
         ...
20936    47.58
20937    47.58
20938    47.58
20939    47.58
20940    47.58
Name: Gross, Length: 20941, dtype: float64

In [53]:

movies_df.rename(columns={
    "Gross": "GROSS(Million)",
    "RunTime":"RUNTIME(Minutes)"
}, inplace=True)
movies_df

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RUNTIME(Minutes),GROSS(Million)
0,Blood Red Sky,2021.0,Action,6.10,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,21062.0,121.0,47.58
1,Blood Red Sky,2021.0,Horror,6.10,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,21062.0,121.0,47.58
2,Blood Red Sky,2021.0,Thriller,6.10,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,21062.0,121.0,47.58
3,Masters of the Universe: Revelation,2021.0,Animation,5.00,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...",17870.0,25.0,47.58
4,Masters of the Universe: Revelation,2021.0,Action,5.00,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...",17870.0,25.0,47.58
...,...,...,...,...,...,...,...,...,...
20936,The Imperfects,2021.0,Drama,6.99,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,7.0,67.3,47.58
20937,The Imperfects,2021.0,Fantasy,6.99,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,7.0,67.3,47.58
20938,The Imperfects,2021.0,Adventure,6.99,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,7.0,67.3,47.58
20939,The Imperfects,2021.0,Drama,6.99,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,7.0,67.3,47.58
20940,The Imperfects,2021.0,Fantasy,6.99,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,7.0,67.3,47.58

In [54]:
movies_df['Director'] = movies_df["STARS"].str.extract(r'Director:\s*([^|]+)')
movies_df['Stars'] = movies_df["STARS"].str.extract(r'Stars:\s*(.*)')
movies_df['Director'] = movies_df['Director'].str.strip()
movies_df['Stars'] = movies_df['Stars'].str.strip()
    
movies_df

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RUNTIME(Minutes),GROSS(Million),Director,Stars
0,Blood Red Sky,2021.0,Action,6.10,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,21062.0,121.0,47.58,Peter Thorwarth,"Peri Baumeister,"
1,Blood Red Sky,2021.0,Horror,6.10,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,21062.0,121.0,47.58,Peter Thorwarth,"Peri Baumeister,"
2,Blood Red Sky,2021.0,Thriller,6.10,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,21062.0,121.0,47.58,Peter Thorwarth,"Peri Baumeister,"
3,Masters of the Universe: Revelation,2021.0,Animation,5.00,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...",17870.0,25.0,47.58,NaN,"Chris Wood,"
4,Masters of the Universe: Revelation,2021.0,Action,5.00,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...",17870.0,25.0,47.58,NaN,"Chris Wood,"
...,...,...,...,...,...,...,...,...,...,...,...
20936,The Imperfects,2021.0,Drama,6.99,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,7.0,67.3,47.58,Jovanka Vuckovic,"Morgan Taylor Campbell,"
20937,The Imperfects,2021.0,Fantasy,6.99,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,7.0,67.3,47.58,Jovanka Vuckovic,"Morgan Taylor Campbell,"
20938,The Imperfects,2021.0,Adventure,6.99,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,7.0,67.3,47.58,Jovanka Vuckovic,"Morgan Taylor Campbell,"
20939,The Imperfects,2021.0,Drama,6.99,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,7.0,67.3,47.58,Jovanka Vuckovic,"Morgan Taylor Campbell,"
20940,The Imperfects,2021.0,Fantasy,6.99,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,7.0,67.3,47.58,Jovanka Vuckovic,"Morgan Taylor Campbell,"

In [55]:
movies_df.duplicated().sum()

np.int64(855)

In [56]:
movies_df = movies_df.drop_duplicates()

In [57]:
movies_df= movies_df.dropna(subset=["Director"], inplace=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_5768\3113035716.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df= movies_df.dropna(subset=["Director"], inplace=True)

In [58]:
plt.hist(movies_df["RATING"], color="purple", edgecolor="white")
plt.title("Distribution of IMDb Ratings Across All Titles")
plt.xlabel("Rating")
plt.ylabel("Number of movies title")
plt.show()

TypeError: 'NoneType' object is not subscriptable

In [ ]:
avg_rating = filtered_df.groupby("YEAR")["RATING"].mean().round(1)
avg_rating
plt.plot(avg_rating.index, avg_rating.values, marker="o", color="green")
plt.title("Moving Average of Movie rating changed over time")
plt.xlabel("Rating")
plt.ylabel("Average IMBD rating")
plt.grid(True, linestyle="--", alpha= 0.7)
plt.show()

In [ ]:
movies_df.groupby("GENRE").agg({
    "GENRE":"count", 
    "RATING":"mean", 
    "VOTES":"sum"})

In [ ]:
corr_runtime_rating = movies_df['RUNTIME(Minutes)'].corr(movies_df['RATING']).round(2)
print(corr_runtime_rating)

In [ ]:
corr_runtime_votes = movies_df['RUNTIME(Minutes)'].corr(movies_df['VOTES']).round(2)
print(corr_runtime_votes)

In [ ]:
high_rated = movies_df[movies_df['RATING'] >= 8.0]
top_directors = high_rated['Director'].value_counts().head(10)
top_directors.reset_index()

In [ ]:
top_by_rating = movies_df.sort_values(by="RATING", ascending=False).head(10)
top_by_rating

In [ ]:
top_by_votes = movies_df.sort_values(by="VOTES", ascending=False).head(10)
top_by_votes

In [ ]:
top_by_Gross= movies_df.sort_values(by="GROSS(Million)", ascending=False).head(10)
top_by_Gross

In [ ]:
avg_votes_genre = movies_df.groupby("GENRE")["VOTES"].count().reset_index()
avg_votes_genre

In [ ]:
avg_votes_year = movies_df.groupby("YEAR")["VOTES"].mean().reset_index()
avg_votes_year

In [ ]:
plt.hist(movies_df["RATING"], color="blue", edgecolor="white")
plt.title("Histogrsm of Rating")
plt.xlabel("Rating")
plt.ylabel("Number of movies title")
plt.show()

In [ ]:
plt.hist(movies_df["VOTES"], color="green", edgecolor="white")
plt.title("Histogrsm of Votes")
plt.xlabel("Votes")
plt.ylabel("Number of movies title")
plt.show()

In [ ]:
plt.hist(movies_df["GROSS(Million)"], color="orange", edgecolor="white")
plt.title("Histogrsm of Gross")
plt.xlabel("GROSS(Million)")
plt.ylabel("Number of movies title")
plt.show()

In [ ]:

top_genres = movies_df["GENRE"].value_counts().head(10)

plt.bar(top_genres.index, top_genres.values, color="lightblue")
plt.title("Top 10 Movie Genres")
plt.xlabel("Genre")
plt.ylabel("Number of Movies")
plt.xticks(rotation=90)
plt.show()

In [ ]:

plt.bar(top_directors.index, top_directors.values, color="orange")
plt.title("Top 10 Movie Directors")
plt.xlabel("Director")
plt.ylabel("Number of Movies")
plt.xticks(rotation=90)
plt.show()

In [ ]:

filtered_df = movies_df[(movies_df['YEAR'] >= 2010) & (movies_df['YEAR'] <= 2022)]

avg_rating = filtered_df.groupby('YEAR')['RATING'].mean().round(1)
plt.plot(avg_rating.index, avg_rating.values, marker='o', color='blue')
plt.title("Average Movie Ratings by Year (2010-2022)")
plt.xlabel("Year")
plt.ylabel("Average IMDb Rating")
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

In [ ]:
numeric_df =movies_df.select_dtypes(include=['float64', 'int64'])
corr_matrix = numeric_df.corr()

numeric_df

In [ ]:
sns.heatmap(corr_matrix, annot=True,fmt=".2f",cmap="vlag", center = 0, linewidth= "0.5",linecolor="blue")
plt.title('Correlation Heatmap of Numeric Features')
plt.show()

In [ ]:
genre_year = filtered_df.groupby(["YEAR", "GENRE"]).size().unstack(fill_value=0)
genre_year = genre_year.div(genre_year.sum(axis=1), axis=0) * 100

genre_year.plot(kind='bar', stacked=True, colormap='tab20', )
plt.title('Genre Distribution (2010–2022)')
plt.xlabel('Year')
plt.ylabel('Percentage')
plt.legend(title='Genre', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()